### ISSUE TITLE
PolymorphicMPTTModel has disparate 'objects' and '_default_manager' managers

### ISSUE THREAD

**Issue by smcoll** [django-polymorphic/django-polymorphic-tree#34]
Came across this error when confirming a delete action in the Django admin.

`mptt.admin.MPTTModelAdmin.delete_selected_tree()` references `object`' as the manager used [(source)](https://github.com/django-mptt/django-mptt/blob/0.7.2/mptt/admin.py#L72), but the default implementation of `PolymorphicMPTTModel` doesn't declare `objects`, rather `_default_manager`.  The end result is that a sublcass of `PolymorphicMPTTModel` has `PolymorphicManager` as the `objects` manager, and `PolymorphicMPTTModelManager` as the `_default_manager` manager.

So when the admin delete_selected_tree() method is reached, there is an AttributeError:

```
AttributeError at /admin/myapp/basetreenode/
'PolymorphicQuerySet' object has no attribute 'delay_mptt_updates'
```

My present workaround is to declare `objects = PolymorphicMPTTModelManager()` on my BaseTreeNode class.

**Comment by vdboor** [comment]
Hi! Which version are you using of django-polymorphic and django-polymorphic-tree? There were a few Django 1.7 fixes in the latest versions, so I want to make sure you have these versions.

**Comment by smcoll** [comment]
Django==1.7.7
django-mptt==0.7.2
django-polymorphic==0.7
django-polymorphic-tree==1.1

**Comment by vdboor** [comment]
This should be fixed with newer polymorphic versions (and newer Django versions). If you still have this issue, please let me know!
