### ISSUE TITLE
`ImportError: No module named manager` in polymorphic_tree/managers.py:7

### ISSUE THREAD

**Issue by 0xCMP** [django-polymorphic/django-polymorphic-tree#61]
For some reason in `django-polymorphic` there is no `managers.py` to import and `polymorphic_tree/managers.py` imports `polymorphic.manager` which is making my project stop working.

Not sure why it stopped working now, but this seems like a weird issue apparently no one has run in to?

https://github.com/django-polymorphic/django-polymorphic-tree/blob/0c30a95fce46d7cfc0643f49d9cbb353f14808aa/polymorphic_tree/managers.py#L7

**Comment by vdboor** [comment]
Thanks for pointing this out! I've fixed this in the 1.4.2 release!

**Comment by maruthi8** [comment]
Modify in the documentation http://django-polymorphic.readthedocs.io/en/stable/managers.html#manager-inheritance 
 This one `from polymorphic.manager import PolymorphicManager` to  from polymorphic.managers import PolymorphicManager

**Comment by vdboor** [comment]
Thanks, @maruthi8  I've fixed this in d3f044871b3236ce3a37bffd2466143c98412dd0!
