### ISSUE TITLE
Attribute from child_models in list_display 

### ISSUE THREAD

**Issue by Dan7ska** [django-polymorphic/django-polymorphic-tree#74]
I want to show in django-admin, attributes from Contents depending on the type of my object.
Part of my models:

	class UserTimelines(PolymorphicMPTTModel):
		parent = PolymorphicTreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True, on_delete=models.CASCADE)

		class Meta(PolymorphicMPTTModel.Meta):
			verbose_name = "User Timeline"
			verbose_name_plural = "User Timelines"

	class Node(UserTimelines):
		node_title = models.CharField(max_length=20, null=True)
		
		to_show = str(node_title)

		class Meta:
			verbose_name = "Node"
			verbose_name_plural = "Nodes"

	class CategoryNode(UserTimelines):
		category_username = models.CharField(max_length=25, null=True)
		
		to_show = str(category_username) + ' timeline'
		
		class Meta:
			verbose_name = "Category node"
			verbose_name_plural = "Category nodes"

And part of my admin.py:

	class BaseChildAdmin(PolymorphicMPTTChildModelAdmin):
		GENERAL_FIELDSET = ( None, {
			'fields' : ('parent',),
		})

		base_model = UserTimelines
		base_fieldsets = (
			GENERAL_FIELDSET,
		)

	class TreeNodeParentAdmin(PolymorphicMPTTParentModelAdmin):
		base_model = UserTimelines
		child_models = (
			(Node),
			(CategoryNode),
		)

		list_display = ('to_show', 'actions_column',)

		class Media:
			css = {
				'all' : ('admin/treenode/admin.css',)
			}

	admin.site.register((Node, CategoryNode),BaseChildAdmin)
	admin.site.register(UserTimelines, TreeNodeParentAdmin)

Summarizing, I want to add to 'list_display', attribute 'to_show', how can I do it?

**Comment by Dan7ska** [comment]
After few days, I make solution for this issue. It is simple anyway, You must do sth like this:

Models.py:

	class UserTimelines(PolymorphicMPTTModel):
	    parent = PolymorphicTreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True, on_delete=models.CASCADE)

	    class Meta(PolymorphicMPTTModel.Meta):
		verbose_name = "User Timeline"
		verbose_name_plural = "User Timelines"

	class Node(UserTimelines):
	    node_title = models.CharField(max_length=20, null=True)
	    
	    def __str__(self):
		return str(self.node_title)

	    class Meta:
		verbose_name = "Node"
		verbose_name_plural = "Nodes"

	class CategoryNode(UserTimelines):
	    category_username = models.CharField(max_length=25, null=True)
	    
	    def __str__(self):
		return str(self.category_username) + ' timetable'

	    class Meta:
		verbose_name = "Category node"
		verbose_name_plural = "Category nodes"

Admin.py:

	class BaseChildAdmin(PolymorphicMPTTChildModelAdmin):
	    GENERAL_FIELDSET = ( None, {
		'fields' : ('parent',),
	    })

	    base_model = UserTimelines
	    base_fieldsets = (
		GENERAL_FIELDSET,
	    )


	class TreeNodeParentAdmin(PolymorphicMPTTParentModelAdmin):
	    base_model = UserTimelines
	    child_models = (
		(Node),
		(CategoryNode),
	    )
	    
	    list_display = ('_show', 'actions_column',)

	    def _show(self, obj):
		return str(UserTimelines.objects.get(pk=obj.pk).__str__())

	    class Media:
		css = {
		    'all' : ('admin/treenode/admin.css',)
		}

	admin.site.register((Node, CategoryNode),BaseChildAdmin)
	admin.site.register(UserTimelines, TreeNodeParentAdmin)

I think this solution can help someone in the future so here you are.

**Comment by BigglesZX** [comment]
Very late to the party, but just in case this helps anyone else: I was able to achieve the above by adding `polymorphic_list = True` to my equivalent of the `TreeNodeParentAdmin` class. As per the docs for [django-polymorphic](https://django-polymorphic.readthedocs.io/en/stable/admin.html#the-parent-model) this causes the list view to retrieve child models, making them available to admin class methods. So in the example above, the `obj` argument to the `_show` method would be the child model, not the base model.
